### PR TITLE
INSTALL.md: add `libleveldb-dev` to required packages

### PR DESCRIPTION
**Pull request by belikor**
With the provided instructions in `INSTALL.md`, the `make` command may result in errors:
```
    plyvel/_plyvel.cpp:589:10: fatal error: leveldb/db.h: No such file or directory
      589 | #include "leveldb/db.h"
          |          ^~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

...
Failed to build plyvel prometheus-client pylru pyyaml.
```

The required header files are contained in the `libleveldb-dev` package in Ubuntu 18.04 and 20.04 at least.

After installing this package the compilation proceeds successfully.
In some cases `make` may have to be run twice.

This addresses issue #3281.

----

Also add more information on entering and exiting the virtual environment.
```
deactivate  # leave
source lbry-venv/bin/activate  # enter
```

To test the daemon interactively, we can run the `cli.py` program.
```
python lbry/extras/cli.py start
```

----

Because of issue #2769 at the moment the `lbrynet` daemon will only work correctly with Python 3.7.

If Python 3.8+ is used, the daemon will start but the RPC server may not accept messages,

### CODE REVIEW

**Review by shyba — APPROVED** [review]

**Comment by belikor** [comment]
This pull request was divided into two, #3357 and #3358.

We think using `plyvel=1.2.0` is a better solution than recommending the installation of `libleveldb-dev` but keeping `plyvel=1.0.5`.
